export const positionSeed = [
  {
    name: 'Front-end developer',
    duties: '',
    requirements: '',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
  },
  {
    name: 'Back-end developer',
    duties: '',
    requirements: '',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
  },
  {
    name: 'Full stack developer',
    duties: '',
    requirements: '',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
  },
  {
    name: 'Front-end trainee',
    duties: '',
    requirements: '',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
  },
  {
    name: 'Back-end trainee',
    duties: '',
    requirements: '',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
  },
  {
    name: 'Full stack trainee',
    duties: '',
    requirements: '',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
  },
  {
    name: 'Swift developer',
    duties: '',
    requirements: '',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
  },
  {
    name: 'Business Development manager',
    duties: '',
    requirements: '',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
  },
  {
    name: 'Marketing Manager',
    duties: '',
    requirements: '',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
  },
  {
    name: 'CEO',
    duties: '',
    requirements: '',
    salaryMinLimit: 100,
    salaryMaxLimit: 1000,
  },
];
