---
application:
  name: "dektry-portal-be"
  project: "dektry-portal"
  organization: "QoveryCommunity"
databases:
- type: "POSTGRESQL"
  name: "dektry-portal"
  version: "12"
routers:
- name: "main-dektry-portal-be"
  routes:
  - application_name: "dektry-portal-be"
    paths:
    - "/*"
