export enum Permissions {
  deleteUsers = 'DELETE_USERS',
  createUser = 'CREATE_USER',
  getUser = 'GET_USER',
  getAllUsers = 'GET_ALL_USERS',
  updateUser = 'UPDATE_USER',
  getAllRoles = 'GET_ALL_ROLES',
  getRoleByName = 'GET_ROLE_BY_NAME',
  createRole = 'CREATE_ROLE',
  updateRole = 'UPDATE_ROLE',
  deleteRole = 'DELETE_ROLE',
  getPermissionByName = 'GET_PERMISSION_BY_NAME',
  createPermission = 'CREATE_PERMISSION',
  getAllPositions = 'GET_ALL_POSITIONS',
  createPosition = 'CREATE_POSITION',
  updatePosition = 'UPDATE_POSITION',
  deletePosition = 'DELETE_POSITION',
}
